//! The guide's model, built from the rust-analyzer index.
//!
//! The index is leading: which crates, modules, types and functions exist, what
//! they are called, their docs, their signatures (and so their visibility), and
//! what every reference resolves to all come from it. The source scan
//! ([`crate::source`]) adds two things the index cannot be trusted with: the
//! exact extent of each function, so a call is placed in the function that makes
//! it, and which code is test code. Test code is left out, as caller and callee.
//!
//! A call is a reference, outside test code, from inside one workspace function
//! to another. It counts a function passed as a value (`.map(Self::f)`) as well
//! as a call: both are uses, and the index does not tell them apart.

use std::collections::{BTreeMap, BTreeSet, HashMap};

use scip::types::descriptor::Suffix;
use scip::types::symbol_information::Kind as ScipKind;
use scip::types::{Index, SymbolRole};
use serde::Serialize;

use crate::source::Sources;

/// A workspace crate, as cargo describes it.
#[derive(Debug, Clone)]
pub struct CrateInput {
    /// The cargo package name, as it appears in index symbols.
    pub package: String,
    /// Short name used in the guide: `engine` for `regelrecht-engine`.
    pub name: String,
    /// Directory relative to the workspace root, `/`-separated.
    pub dir: String,
    pub description: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum TypeKind {
    Struct,
    Enum,
    Trait,
    Union,
    Alias,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Vis {
    /// `pub`.
    Pub,
    /// `pub(crate)`, `pub(super)`, `pub(in ..)`.
    Restricted,
    /// No visibility keyword.
    Private,
    /// A method of a trait implementation: as visible as the trait.
    Trait,
}

/// Visibility, read off the signature rust-analyzer prints for the item.
pub fn vis_of(signature: &str, trait_impl: bool) -> Vis {
    if trait_impl {
        return Vis::Trait;
    }
    let s = signature.trim_start();
    if s.starts_with("pub(") {
        Vis::Restricted
    } else if s.starts_with("pub ") {
        Vis::Pub
    } else {
        Vis::Private
    }
}

/// Where an item is defined: a file relative to the workspace, a 1-based line.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Place {
    pub file: String,
    pub line: usize,
}

#[derive(Debug, Clone, Serialize)]
pub struct Module {
    pub krate: String,
    /// `::`-separated, `""` for the crate root, `bin:<name>` for a binary root.
    pub path: String,
    pub docs: Option<String>,
    pub vis: Vis,
    pub file: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct TypeItem {
    pub krate: String,
    pub module: String,
    pub name: String,
    pub kind: TypeKind,
    pub signature: String,
    pub docs: Option<String>,
    pub vis: Vis,
    pub place: Place,
    /// 1-based, inclusive, doc comment through closing brace: the extent the
    /// index gives the definition. Used to show the type's source.
    pub extent: Option<(usize, usize)>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Function {
    /// Unique and readable: `engine::service::LawExecutionService::evaluate_law`,
    /// with `@Trait` after the name for a trait implementation's method.
    pub id: String,
    pub krate: String,
    pub module: String,
    /// The type (or trait) the function belongs to, if any.
    pub owner: Option<String>,
    /// For a method of a trait implementation, the trait.
    #[serde(rename = "trait")]
    pub trait_name: Option<String>,
    pub name: String,
    pub signature: String,
    pub docs: Option<String>,
    pub vis: Vis,
    pub place: Place,
    /// Defined in a file that changed since the index was built: what the guide
    /// shows is as indexed, and the file's current text may differ.
    pub stale: bool,
    /// 1-based, inclusive; from the source. `None` for a function the source
    /// scan did not see (generated by a macro): it can be called but cannot be
    /// shown to call anything.
    pub extent: Option<(usize, usize)>,
}

/// What building the model left out, so the guide can say so.
#[derive(Debug, Default, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Counts {
    pub functions: usize,
    pub types: usize,
    pub calls: usize,
    pub call_sites: usize,
    /// References to a workspace function from test code (left out).
    pub test_references: usize,
    /// References outside any function (a `const`, a `static`, a module-level
    /// attribute): there is no caller to draw them from.
    pub outside_functions: usize,
    /// References to a symbol the index defines more than once (two binaries
    /// each with a `main`): the callee cannot be told, so the call is dropped.
    pub ambiguous: usize,
    /// Files that changed since the index was built. The guide shows them as
    /// they were indexed; their source view may not match.
    pub stale_files: Vec<String>,
    /// Functions and types defined inside a function body. rust-analyzer gives
    /// them a module-level symbol, but they are part of the function they sit
    /// in, so they are left out (and calls to them are calls within it).
    pub nested: usize,
}

#[derive(Debug, Default)]
pub struct Model {
    pub crates: Vec<CrateInput>,
    pub crate_docs: BTreeMap<String, String>,
    pub modules: BTreeMap<(String, String), Module>,
    pub types: Vec<TypeItem>,
    pub functions: Vec<Function>,
    /// (caller, callee) -> number of call sites, indexes into `functions`.
    pub calls: BTreeMap<(usize, usize), usize>,
    pub counts: Counts,
}

/// What a workspace symbol is, from its descriptors.
#[derive(Debug, PartialEq, Eq)]
enum Shape {
    Module(Vec<String>),
    Type {
        module: Vec<String>,
        name: String,
    },
    Function {
        module: Vec<String>,
        owner: Option<String>,
        trait_name: Option<String>,
        name: String,
    },
    Other,
}

/// Splits a parsed symbol's descriptors into module path, owner and name.
/// rust-analyzer writes an inherent method as `ns/impl#[Type]name().`, a trait
/// implementation's method as `ns/impl#[Type][Trait]name().`, a trait's own
/// method as `ns/Trait#name().`, and a free function as `ns/name().`.
fn shape(descriptors: &[scip::types::Descriptor]) -> Shape {
    let mut module = Vec::new();
    let mut i = 0;
    while let Some(d) = descriptors.get(i) {
        if d.suffix.enum_value_or_default() != Suffix::Namespace {
            break;
        }
        module.push(d.name.clone());
        i += 1;
    }
    let rest = &descriptors[i..];
    let suffix = |d: &scip::types::Descriptor| d.suffix.enum_value_or_default();
    match rest {
        [] => Shape::Module(module),
        [t] if suffix(t) == Suffix::Type && t.name != "impl" => Shape::Type {
            module,
            name: t.name.clone(),
        },
        [f] if suffix(f) == Suffix::Method => Shape::Function {
            module,
            owner: None,
            trait_name: None,
            name: f.name.clone(),
        },
        [t, f] if suffix(t) == Suffix::Type && t.name != "impl" && suffix(f) == Suffix::Method => {
            Shape::Function {
                module,
                owner: Some(t.name.clone()),
                trait_name: None,
                name: f.name.clone(),
            }
        }
        [imp, params @ .., f]
            if suffix(imp) == Suffix::Type
                && imp.name == "impl"
                && suffix(f) == Suffix::Method
                && !params.is_empty()
                && params.iter().all(|p| suffix(p) == Suffix::TypeParameter) =>
        {
            Shape::Function {
                module,
                // `impl<'a> Ctx<'a>` is written `impl#[Ctx<'a>]`: the type is
                // `Ctx`. A trait keeps its arguments, because `From<A>` and
                // `From<B>` are two implementations with a `from` each.
                owner: Some(strip_generics(&params[0].name)),
                trait_name: params.get(1).map(|p| p.name.clone()),
                name: f.name.clone(),
            }
        }
        _ => Shape::Other,
    }
}

/// A SCIP range (`[line, col, end_col]` or `[line, col, end_line, end_col]`,
/// 0-based) as 1-based first and last line.
fn enclosing(range: &[i32]) -> Option<(usize, usize)> {
    match range {
        [l, _, _] => Some((*l as usize + 1, *l as usize + 1)),
        [l, _, e, _] => Some((*l as usize + 1, *e as usize + 1)),
        _ => None,
    }
}

/// `Ctx<'a>` -> `Ctx`.
fn strip_generics(name: &str) -> String {
    name.split('<').next().unwrap_or(name).trim().to_string()
}

const FUNCTION_KINDS: [ScipKind; 6] = [
    ScipKind::Function,
    ScipKind::Method,
    ScipKind::StaticMethod,
    ScipKind::TraitMethod,
    ScipKind::AbstractMethod,
    ScipKind::Constructor,
];

fn type_kind(kind: ScipKind) -> Option<TypeKind> {
    Some(match kind {
        ScipKind::Struct => TypeKind::Struct,
        ScipKind::Enum => TypeKind::Enum,
        ScipKind::Trait | ScipKind::Interface => TypeKind::Trait,
        ScipKind::Union => TypeKind::Union,
        ScipKind::TypeAlias => TypeKind::Alias,
        _ => return None,
    })
}

fn docs_of(info: &scip::types::SymbolInformation) -> Option<String> {
    let text = info.documentation.join("\n\n");
    let text = text.trim();
    (!text.is_empty()).then(|| text.to_string())
}

/// Where a binary's code lives: a file under `src/bin/` is a root of its own,
/// so its items get a `bin:<name>` module. The index puts them at the crate's
/// root, where two binaries' `main` would be the same item.
fn bin_root(file: &str, crate_dir: &str) -> Option<String> {
    let rest = file.strip_prefix(crate_dir)?.strip_prefix("/src/bin/")?;
    let name = rest.split('/').next()?.trim_end_matches(".rs");
    Some(format!("bin:{name}"))
}

fn join_module(bin: Option<String>, ns: &[String]) -> String {
    bin.into_iter()
        .chain(ns.iter().cloned())
        .collect::<Vec<_>>()
        .join("::")
}

impl Model {
    /// Builds the model from the index, the workspace's crates and the scanned
    /// sources.
    pub fn build(
        index: &Index,
        crates: Vec<CrateInput>,
        sources: &Sources,
        changed: &BTreeSet<String>,
    ) -> Model {
        let by_package: HashMap<&str, &CrateInput> =
            crates.iter().map(|c| (c.package.as_str(), c)).collect();
        let mut model = Model {
            crates: crates.clone(),
            ..Model::default()
        };

        // Symbol information is attached to the document that defines the symbol.
        let mut info: HashMap<&str, &scip::types::SymbolInformation> = HashMap::new();
        for doc in &index.documents {
            for s in &doc.symbols {
                info.entry(s.symbol.as_str()).or_insert(s);
            }
        }

        // Every definition of a workspace symbol, with where it is.
        let mut fn_by_symbol: HashMap<&str, Vec<usize>> = HashMap::new();
        let mut fn_by_site: HashMap<(&str, usize), usize> = HashMap::new();
        for doc in &index.documents {
            let file = doc.relative_path.as_str();
            for occ in &doc.occurrences {
                if occ.symbol_roles & SymbolRole::Definition as i32 == 0 || occ.range.is_empty() {
                    continue;
                }
                let line = occ.range[0] as usize + 1;
                if !sources.knows(file) || sources.is_test_at(file, line) {
                    continue;
                }
                let Ok(parsed) = scip::symbol::parse_symbol(&occ.symbol) else {
                    continue;
                };
                let Some(krate) = by_package.get(parsed.package.name.as_str()) else {
                    continue;
                };
                let Some(si) = info.get(occ.symbol.as_str()) else {
                    continue;
                };
                let kind = si.kind.enum_value_or_default();
                let signature = si.signature_documentation.text.clone();
                let bin = bin_root(file, &krate.dir);
                match shape(&parsed.descriptors) {
                    Shape::Module(ns) if kind == ScipKind::Module || ns.is_empty() => {
                        // rust-analyzer names the crate root `crate/`.
                        let ns: Vec<String> = if ns == ["crate"] { Vec::new() } else { ns };
                        if ns.is_empty() {
                            if let Some(d) = docs_of(si) {
                                model.crate_docs.entry(krate.name.clone()).or_insert(d);
                            }
                            continue;
                        }
                        let path = join_module(bin, &ns);
                        model
                            .modules
                            .entry((krate.name.clone(), path.clone()))
                            .or_insert(Module {
                                krate: krate.name.clone(),
                                path,
                                docs: docs_of(si),
                                vis: vis_of(&signature, false),
                                file: None,
                            });
                    }
                    Shape::Type { module, name } => {
                        let Some(tk) = type_kind(kind) else { continue };
                        if nested_in_fn(sources, file, line) {
                            model.counts.nested += 1;
                            continue;
                        }
                        model.types.push(TypeItem {
                            krate: krate.name.clone(),
                            module: join_module(bin, &module),
                            name,
                            kind: tk,
                            vis: vis_of(&signature, false),
                            signature,
                            docs: docs_of(si),
                            place: Place {
                                file: file.to_string(),
                                line,
                            },
                            extent: enclosing(&occ.enclosing_range)
                                .filter(|_| !changed.contains(file)),
                        });
                    }
                    Shape::Function {
                        module,
                        owner,
                        trait_name,
                        name,
                    } if FUNCTION_KINDS.contains(&kind) => {
                        let stale = changed.contains(file);
                        let site = sources.fn_named_at(file, line, &name);
                        if site.is_some_and(|s| s.test) {
                            continue;
                        }
                        // A function the scan does not have at this line, inside
                        // another function's body, is nested in it.
                        if site.is_none() && nested_in_fn(sources, file, line) {
                            model.counts.nested += 1;
                            continue;
                        }
                        let module = join_module(bin, &module);
                        let mut id = vec![krate.name.clone()];
                        id.extend(
                            module
                                .split("::")
                                .filter(|s| !s.is_empty())
                                .map(str::to_string),
                        );
                        id.extend(owner.clone());
                        id.push(match &trait_name {
                            Some(t) => format!("{name}@{t}"),
                            None => name.clone(),
                        });
                        let f = Function {
                            id: id.join("::"),
                            krate: krate.name.clone(),
                            module,
                            vis: vis_of(&signature, trait_name.is_some()),
                            owner,
                            trait_name,
                            name,
                            signature,
                            docs: docs_of(si),
                            place: Place {
                                file: file.to_string(),
                                line,
                            },
                            stale,
                            extent: site.map(|s| (s.line, s.end_line)),
                        };
                        let idx = model.functions.len();
                        if let Some(s) = site {
                            fn_by_site.insert((file, s.name_line), idx);
                        }
                        fn_by_symbol
                            .entry(occ.symbol.as_str())
                            .or_default()
                            .push(idx);
                        model.functions.push(f);
                    }
                    _ => {}
                }
            }
        }

        // Every module that holds an item exists, even if the index has no
        // symbol for the module itself (a binary root, an inline module).
        let holders: Vec<(String, String)> = model
            .types
            .iter()
            .map(|t| (t.krate.clone(), t.module.clone()))
            .chain(
                model
                    .functions
                    .iter()
                    .map(|f| (f.krate.clone(), f.module.clone())),
            )
            .collect();
        for (krate, path) in holders {
            model
                .modules
                .entry((krate.clone(), path.clone()))
                .or_insert(Module {
                    krate,
                    path: path.clone(),
                    docs: None,
                    vis: if path.is_empty() || path.starts_with("bin:") {
                        Vis::Pub
                    } else {
                        Vis::Private
                    },
                    file: None,
                });
        }
        for m in model.modules.values_mut() {
            if let Some(c) = crates.iter().find(|c| c.name == m.krate) {
                m.file = module_file(sources, &c.dir, &m.path);
            }
        }

        // Calls: every reference to a workspace function, from inside another.
        for doc in &index.documents {
            let file = doc.relative_path.as_str();
            for occ in &doc.occurrences {
                let roles = occ.symbol_roles;
                if roles & (SymbolRole::Definition as i32 | SymbolRole::Import as i32) != 0
                    || occ.range.is_empty()
                {
                    continue;
                }
                let Some(callees) = fn_by_symbol.get(occ.symbol.as_str()) else {
                    continue;
                };
                let line = occ.range[0] as usize + 1;
                if !sources.knows(file) || sources.is_test_at(file, line) {
                    model.counts.test_references += 1;
                    continue;
                }
                // rust-analyzer does not always mark a `use` path as an import.
                if sources.is_import_at(file, line) {
                    continue;
                }
                let Some(site) = sources.enclosing_fn(file, line) else {
                    model.counts.outside_functions += 1;
                    continue;
                };
                if site.test {
                    model.counts.test_references += 1;
                    continue;
                }
                let Some(&caller) = fn_by_site.get(&(file, site.name_line)) else {
                    model.counts.outside_functions += 1;
                    continue;
                };
                let [callee] = callees.as_slice() else {
                    model.counts.ambiguous += 1;
                    continue;
                };
                if caller != *callee {
                    *model.calls.entry((caller, *callee)).or_insert(0) += 1;
                }
            }
        }

        model.counts.stale_files = changed.iter().cloned().collect();
        model.counts.functions = model.functions.len();
        model.counts.types = model.types.len();
        model.counts.calls = model.calls.len();
        model.counts.call_sites = model.calls.values().sum();
        model
            .types
            .sort_by(|a, b| (&a.krate, &a.module, &a.name).cmp(&(&b.krate, &b.module, &b.name)));
        model
    }
}

/// The file a module lives in, by the usual layout: `src/a/b.rs` or
/// `src/a/b/mod.rs`; the root is `src/lib.rs` (or `src/main.rs`); a binary
/// root is `src/bin/<name>.rs` (or `src/bin/<name>/main.rs`). `None` for an
/// inline module, which has no file of its own.
fn module_file(sources: &Sources, crate_dir: &str, path: &str) -> Option<String> {
    let mut segs: Vec<&str> = path.split("::").filter(|s| !s.is_empty()).collect();
    let mut base = format!("{crate_dir}/src");
    if let Some(bin) = segs.first().and_then(|s| s.strip_prefix("bin:")) {
        base = format!("{base}/bin");
        let rest: Vec<&str> = segs.split_off(1);
        if rest.is_empty() {
            return [format!("{base}/{bin}.rs"), format!("{base}/{bin}/main.rs")]
                .into_iter()
                .find(|f| sources.knows(f));
        }
        base = format!("{base}/{bin}");
        segs = rest;
    }
    if segs.is_empty() {
        return [format!("{base}/lib.rs"), format!("{base}/main.rs")]
            .into_iter()
            .find(|f| sources.knows(f));
    }
    let stem = format!("{base}/{}", segs.join("/"));
    [format!("{stem}.rs"), format!("{stem}/mod.rs")]
        .into_iter()
        .find(|f| sources.knows(f))
}

/// The set of modules each module calls into, by `(crate, module)`.
pub fn module_calls(
    model: &Model,
) -> BTreeMap<(String, String), BTreeMap<(String, String), usize>> {
    let mut out: BTreeMap<(String, String), BTreeMap<(String, String), usize>> = BTreeMap::new();
    for (&(a, b), &n) in &model.calls {
        let (fa, fb) = (&model.functions[a], &model.functions[b]);
        let from = (fa.krate.clone(), fa.module.clone());
        let to = (fb.krate.clone(), fb.module.clone());
        if from != to {
            *out.entry(from).or_default().entry(to).or_insert(0) += n;
        }
    }
    out
}

/// The crates each crate calls into.
pub fn crate_calls(model: &Model) -> BTreeMap<String, BTreeMap<String, usize>> {
    let mut out: BTreeMap<String, BTreeMap<String, usize>> = BTreeMap::new();
    for (&(a, b), &n) in &model.calls {
        let (fa, fb) = (&model.functions[a], &model.functions[b]);
        if fa.krate != fb.krate {
            *out.entry(fa.krate.clone())
                .or_default()
                .entry(fb.krate.clone())
                .or_insert(0) += n;
        }
    }
    out
}

/// Dependency map (node -> nodes it calls) over `nodes`, from weighted edges.
pub fn deps_of(
    nodes: impl IntoIterator<Item = String>,
    edges: impl IntoIterator<Item = (String, String)>,
) -> BTreeMap<String, BTreeSet<String>> {
    let mut d: BTreeMap<String, BTreeSet<String>> =
        nodes.into_iter().map(|n| (n, BTreeSet::new())).collect();
    for (a, b) in edges {
        if d.contains_key(&a) && d.contains_key(&b) && a != b {
            d.entry(a).or_default().insert(b);
        }
    }
    d
}

/// Whether `line` lies in the body of a function, below its name: an item
/// defined there is nested in it. The function's own name line (and a
/// signature-only trait method on the same line as its trait) is not.
fn nested_in_fn(sources: &Sources, file: &str, line: usize) -> bool {
    sources
        .enclosing_fn(file, line)
        .is_some_and(|f| line > f.name_line)
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::testutil::Dir;
    use protobuf::{EnumOrUnknown, MessageField};
    use scip::types::{Document, Occurrence, Signature, SymbolInformation};

    const PKG: &str = "regelrecht-x";

    fn sym(desc: &str) -> String {
        format!("rust-analyzer cargo {PKG} 0.1.0 {desc}")
    }

    /// A symbol's definition at `line` (1-based) and its information.
    fn def(doc: &mut Document, desc: &str, line: usize, kind: ScipKind, signature: &str) {
        let s = sym(desc);
        doc.occurrences.push(Occurrence {
            range: vec![line as i32 - 1, 4, 10],
            symbol: s.clone(),
            symbol_roles: SymbolRole::Definition as i32,
            ..Default::default()
        });
        doc.symbols.push(SymbolInformation {
            symbol: s,
            kind: EnumOrUnknown::new(kind),
            documentation: vec![format!("Docs of {desc}.")],
            signature_documentation: MessageField::some(Signature {
                text: signature.to_string(),
                ..Default::default()
            }),
            ..Default::default()
        });
    }

    fn reference(doc: &mut Document, desc: &str, line: usize) {
        doc.occurrences.push(Occurrence {
            range: vec![line as i32 - 1, 8, 12],
            symbol: sym(desc),
            ..Default::default()
        });
    }

    fn crate_x() -> Vec<CrateInput> {
        vec![CrateInput {
            package: PKG.to_string(),
            name: "x".to_string(),
            dir: "x".to_string(),
            description: None,
        }]
    }

    /// The source both the scan and the synthetic index describe:
    ///
    ///  1 use crate::helpers::util;
    ///  2 pub struct S;
    ///  3 impl S {
    ///  4     pub fn a(&self) {
    ///  5         self.b();
    ///  6         util();
    ///  7     }
    ///  8     fn b(&self) {}
    ///  9 }
    /// 10 impl Tr for S {
    /// 11     fn t(&self) { self.a(); }
    /// 12 }
    /// 13 pub trait Tr { fn t(&self); }
    /// 14 pub fn util() {}
    /// 15 #[cfg(test)]
    /// 16 mod tests {
    /// 17     fn helper() { super::util(); }
    /// 18 }
    const LIB: &str = "use crate::helpers::util;\npub struct S;\nimpl S {\n    pub fn a(&self) {\n        self.b();\n        util();\n    }\n    fn b(&self) {}\n}\nimpl Tr for S {\n    fn t(&self) { self.a(); }\n}\npub trait Tr { fn t(&self); }\npub fn util() {}\n#[cfg(test)]\nmod tests {\n    fn helper() { super::util(); }\n}\n";

    fn build(extra: impl FnOnce(&mut Document)) -> (Dir, Model) {
        let d = Dir::new();
        d.write("x/src/lib.rs", LIB);
        let mut doc = Document {
            relative_path: "x/src/lib.rs".to_string(),
            ..Default::default()
        };
        def(&mut doc, "S#", 2, ScipKind::Struct, "pub struct S");
        def(
            &mut doc,
            "impl#[S]a().",
            4,
            ScipKind::Method,
            "pub fn a(&self)",
        );
        def(&mut doc, "impl#[S]b().", 8, ScipKind::Method, "fn b(&self)");
        def(
            &mut doc,
            "impl#[S][Tr]t().",
            11,
            ScipKind::Method,
            "fn t(&self)",
        );
        def(&mut doc, "Tr#", 13, ScipKind::Trait, "pub trait Tr");
        def(
            &mut doc,
            "Tr#t().",
            13,
            ScipKind::TraitMethod,
            "pub fn t(&self)",
        );
        def(&mut doc, "util().", 14, ScipKind::Function, "pub fn util()");
        def(
            &mut doc,
            "tests/helper().",
            17,
            ScipKind::Function,
            "fn helper()",
        );
        reference(&mut doc, "util().", 1); // the `use`
        reference(&mut doc, "impl#[S]b().", 5);
        reference(&mut doc, "util().", 6);
        reference(&mut doc, "impl#[S]a().", 11);
        reference(&mut doc, "util().", 17); // from test code
        extra(&mut doc);
        let index = Index {
            documents: vec![doc],
            ..Default::default()
        };
        let sources = Sources::scan(d.path(), &["x".to_string()]);
        let model = Model::build(&index, crate_x(), &sources, &BTreeSet::new());
        (d, model)
    }

    fn calls(m: &Model) -> Vec<(String, String, usize)> {
        m.calls
            .iter()
            .map(|(&(a, b), &n)| (m.functions[a].id.clone(), m.functions[b].id.clone(), n))
            .collect()
    }

    #[test]
    fn every_function_shape_gets_its_owner_trait_and_id() {
        let (_d, m) = build(|_| {});
        let ids: Vec<&str> = m.functions.iter().map(|f| f.id.as_str()).collect();
        assert_eq!(
            ids,
            ["x::S::a", "x::S::b", "x::S::t@Tr", "x::Tr::t", "x::util"]
        );
        let t = m.functions.iter().find(|f| f.id == "x::S::t@Tr").unwrap();
        assert_eq!(
            (t.owner.as_deref(), t.trait_name.as_deref(), t.vis),
            (Some("S"), Some("Tr"), Vis::Trait)
        );
        let b = m.functions.iter().find(|f| f.name == "b").unwrap();
        assert_eq!(b.vis, Vis::Private);
        assert_eq!(b.docs.as_deref(), Some("Docs of impl#[S]b().."));
    }

    #[test]
    fn calls_are_placed_in_the_function_that_makes_them() {
        let (_d, m) = build(|_| {});
        assert_eq!(
            calls(&m),
            [
                ("x::S::a".to_string(), "x::S::b".to_string(), 1),
                ("x::S::a".to_string(), "x::util".to_string(), 1),
                ("x::S::t@Tr".to_string(), "x::S::a".to_string(), 1),
            ]
        );
    }

    #[test]
    fn test_code_is_left_out_as_caller_and_as_callee() {
        let (_d, m) = build(|_| {});
        assert!(m.functions.iter().all(|f| f.name != "helper"));
        assert_eq!(m.counts.test_references, 1);
    }

    #[test]
    fn a_use_item_is_not_a_call() {
        let (_d, m) = build(|_| {});
        assert_eq!(m.counts.outside_functions, 0);
        assert!(calls(&m).iter().all(|(a, _, _)| a != "x::util"));
    }

    #[test]
    fn repeated_calls_count_their_sites() {
        let (_d, m) = build(|doc| reference(doc, "impl#[S]b().", 6));
        let ab = calls(&m)
            .into_iter()
            .find(|(a, b, _)| a == "x::S::a" && b == "x::S::b")
            .unwrap();
        assert_eq!(ab.2, 2);
    }

    #[test]
    fn a_call_to_a_symbol_defined_twice_is_dropped_and_counted() {
        // Two definitions of one symbol, as rust-analyzer writes for two binaries' `main`.
        let (_d, m) = build(|doc| {
            def(doc, "util().", 8, ScipKind::Function, "pub fn util()");
        });
        assert_eq!(m.counts.ambiguous, 1);
        assert!(calls(&m).iter().all(|(_, b, _)| !b.ends_with("util")));
    }

    #[test]
    fn a_function_the_source_scan_does_not_know_is_kept_without_extent() {
        // Defined on a line where the source has no function: a macro made it.
        let (_d, m) = build(|doc| {
            def(
                doc,
                "generated().",
                2,
                ScipKind::Function,
                "pub fn generated()",
            )
        });
        let g = m.functions.iter().find(|f| f.name == "generated").unwrap();
        assert_eq!(g.extent, None);
    }

    #[test]
    fn a_file_changed_since_the_index_is_shown_as_indexed_and_marked() {
        // The scan is the one taken with the index, so the calls still hold;
        // the file is only marked as changed since.
        let d = Dir::new();
        d.write("x/src/lib.rs", LIB);
        let mut doc = Document {
            relative_path: "x/src/lib.rs".to_string(),
            ..Default::default()
        };
        def(
            &mut doc,
            "impl#[S]a().",
            4,
            ScipKind::Method,
            "pub fn a(&self)",
        );
        def(&mut doc, "impl#[S]b().", 8, ScipKind::Method, "fn b(&self)");
        reference(&mut doc, "impl#[S]b().", 5);
        let index = Index {
            documents: vec![doc],
            ..Default::default()
        };
        let sources = Sources::scan(d.path(), &["x".to_string()]);
        let changed: BTreeSet<String> = ["x/src/lib.rs".to_string()].into();
        let m = Model::build(&index, crate_x(), &sources, &changed);
        assert_eq!(m.calls.len(), 1);
        assert!(m.functions.iter().all(|f| f.stale && f.extent.is_some()));
        assert_eq!(m.counts.stale_files, ["x/src/lib.rs"]);
    }

    #[test]
    fn functions_and_types_nested_in_a_function_body_are_left_out() {
        // Line 5 is inside `a`'s body; the scan has no function named there.
        let (_d, m) = build(|doc| {
            def(doc, "inner().", 5, ScipKind::Function, "fn inner()");
            def(doc, "Local#", 6, ScipKind::Struct, "struct Local");
        });
        assert!(m.functions.iter().all(|f| f.name != "inner"));
        assert!(m.types.iter().all(|t| t.name != "Local"));
        assert_eq!(m.counts.nested, 2);
    }

    #[test]
    fn a_generic_impl_belongs_to_its_type_and_trait_arguments_stay() {
        let d = |name: &str, suffix: Suffix| scip::types::Descriptor {
            name: name.to_string(),
            suffix: protobuf::EnumOrUnknown::new(suffix),
            ..Default::default()
        };
        let got = shape(&[
            d("m", Suffix::Namespace),
            d("impl", Suffix::Type),
            d("Ctx<'a>", Suffix::TypeParameter),
            d("From<String>", Suffix::TypeParameter),
            d("from", Suffix::Method),
        ]);
        assert_eq!(
            got,
            Shape::Function {
                module: vec!["m".to_string()],
                owner: Some("Ctx".to_string()),
                trait_name: Some("From<String>".to_string()),
                name: "from".to_string(),
            }
        );
    }

    #[test]
    fn visibility_comes_from_the_signature() {
        assert_eq!(vis_of("pub fn f()", false), Vis::Pub);
        assert_eq!(vis_of("pub(crate) fn f()", false), Vis::Restricted);
        assert_eq!(vis_of("fn f()", false), Vis::Private);
        assert_eq!(vis_of("fn f()", true), Vis::Trait);
    }

    #[test]
    fn a_binary_gets_a_module_of_its_own() {
        assert_eq!(
            bin_root("x/src/bin/tool.rs", "x").as_deref(),
            Some("bin:tool")
        );
        assert_eq!(
            bin_root("x/src/bin/tool/main.rs", "x").as_deref(),
            Some("bin:tool")
        );
        assert_eq!(bin_root("x/src/lib.rs", "x"), None);
    }

    #[test]
    fn module_and_crate_calls_are_lifted_from_function_calls() {
        let (_d, m) = build(|_| {});
        // Everything here is in one module of one crate, so nothing lifts.
        assert!(module_calls(&m).is_empty());
        assert!(crate_calls(&m).is_empty());
    }
}
